name: Test to build Docker image

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.ruby_version }}-${{ matrix.freebsd_version }} ${{ matrix.arch }}
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        freebsd_version:
          - "15.0"
          - "14.2"
        ruby_version:
          - 3.2.8
          - 3.3.7
          - 3.4.2
          - master
        arch:
          - amd64
          - arm64

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build image
        run: |
          rake docker:build arch=${{ matrix.arch }} ruby_version=${{ matrix.ruby_version }} freebsd_version=${{ matrix.freebsd_version }}

      - name: Check image
        run: |
          docker images
          docker run ghcr.io/labtec/ruby:${{ matrix.ruby_version }}-${{ matrix.freebsd_version }} ruby -v
